# Generated by Django 6.0.3 on 2026-03-23 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stockuniverse'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockuniverse',
            new_name='stocks_stoc_market_0c176e_idx',
            old_name='stocks_stoc_market_c95adf_idx',
        ),
    ]
