# Generated by Django 6.0.3 on 2026-03-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_stockcatalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockUniverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('market', models.CharField(choices=[('IN', 'Indian'), ('US', 'US')], max_length=2)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['market', 'display_order', 'symbol'],
            },
        ),
        migrations.RenameIndex(
            model_name='stockcatalog',
            new_name='stocks_stoc_market_041fdc_idx',
            old_name='stocks_stoc_market_0f17e7_idx',
        ),
        migrations.RenameIndex(
            model_name='stockcatalog',
            new_name='stocks_stoc_symbol_e7f9c9_idx',
            old_name='stocks_stoc_symbol_47252c_idx',
        ),
        migrations.AddIndex(
            model_name='stockuniverse',
            index=models.Index(fields=['market', 'is_active', 'display_order'], name='stocks_stoc_market_0c176e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockuniverse',
            unique_together={('symbol', 'market')},
        ),
    ]
