# Generated by Django 6.0.3 on 2026-03-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_userprofile_telegram_chat_id_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mpin_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mpin_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_handle',
            field=models.CharField(blank=True, help_text="User's Telegram @username for further communication.", max_length=64, null=True),
        ),
    ]
