# Generated by Django 6.0.3 on 2026-03-21 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_timeseriesforecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(default='3M', max_length=32)),
                ('mean_return', models.FloatField()),
                ('std_dev', models.FloatField()),
                ('sharpe_ratio', models.FloatField()),
                ('total_return', models.FloatField()),
                ('best_stock', models.CharField(blank=True, max_length=32)),
                ('worst_stock', models.CharField(blank=True, max_length=32)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_analyses', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('stars', models.PositiveSmallIntegerField()),
                ('label', models.CharField(blank=True, max_length=32)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
    ]
