import api from './axios.js'

function isAutoGeneratedPortfolio(portfolio) {
  const desc = String(portfolio?.description || '').toLowerCase()
  return desc.includes('auto-generated from stock_universe symbols in sector')
}

export async function fetchPortfolio() {
  const res = await api.get('portfolio/')
  const items = Array.isArray(res.data) ? res.data : []
  return items.filter((p) => !isAutoGeneratedPortfolio(p))
}

export async function fetchPortfolioById(portfolioId) {
  const res = await api.get(`portfolio/${portfolioId}/`)
  return res.data
}

export async function fetchPortfolioLinearRegression(portfolioId) {
  const res = await api.get(`portfolio/${portfolioId}/linear-regression/`)
  return res.data
}

export async function fetchPortfolioLogisticRegression(portfolioId) {
  const res = await api.get(`portfolio/${portfolioId}/logistic-regression/`)
  return res.data
}

export async function fetchPortfolioTimeSeriesForecast(portfolioId, symbol, horizonDays = 1, modelType = 'ARIMA') {
  const res = await api.post(
    `portfolio/${portfolioId}/time-series-forecast/`,
    { symbol, horizon_days: horizonDays, model_type: modelType },
    { timeout: 120000 }
  )
  return res.data
}

export async function fetchMetalsCorrelation(period = '5y', interval = '1d') {
  const res = await api.get('eda/metals/correlation/', { params: { period, interval } })
  return res.data
}

export async function fetchNiftyClusters(period = '1y', interval = '1d') {
  const res = await api.get('eda/nifty/clusters/', { params: { period, interval }, timeout: 120000 })
  return res.data
}

export async function createPortfolio(payload) {
  const res = await api.post('portfolio/', payload)
  return res.data
}

export async function deletePortfolio(portfolioId) {
  await api.delete(`portfolio/${portfolioId}/`)
}

export async function fetchPortfolioClusters(portfolioId) {
  const res = await api.get(`portfolio/${portfolioId}/portfolio-clusters/`, { timeout: 60000 })
  return res.data
}

export async function fetchGrowthAnalysis(portfolioId) {
  const res = await api.get(`portfolio/${portfolioId}/growth-analysis/`, { timeout: 60000 })
  return res.data
}

export async function fetchPortfolioRating(portfolioId) {
  const res = await api.get(`portfolio/${portfolioId}/portfolio-rating/`, { timeout: 60000 })
  return res.data
}

export async function fetchSummaryReport(portfolioId) {
  const res = await api.get(`portfolio/${portfolioId}/summary-report/`, { timeout: 60000 })
  return res.data
}

export async function fetchRecommendStocks(portfolioId) {
  const res = await api.get(`portfolio/${portfolioId}/recommend-stocks/`, { timeout: 60000 })
  return res.data
}

export async function addStockToPortfolio(portfolioId, symbol, quantity, purchase_price, purchase_date) {
  const res = await api.post(`portfolio/${portfolioId}/add-stock/`, {
    symbol, quantity, purchase_price, purchase_date
  })
  return res.data
}

export async function removeStockFromPortfolio(portfolioId, symbol) {
  const res = await api.post(`portfolio/${portfolioId}/remove-stock/`, { symbol })
  return res.data
}

export async function fetchStocks(portfolioId) {
  const res = await api.get('stocks/', { params: { portfolio_id: portfolioId } })
  return res.data
}

export async function fetchStockUniverse(market, includeInactive = false) {
  const params = {}
  if (market) params.market = market
  if (includeInactive) params.include_inactive = 1
  const res = await api.get('stocks/universe/', { params })
  return res.data
}

export async function fetchRecommendedPortfolios(market) {
  const params = {}
  if (market) params.market = market
  const res = await api.get('stocks/recommended-portfolios/', { params })
  return res.data
}

export async function searchLiveStocks(query, limit = 10) {
  const res = await api.get('stocks/live-search/', { params: { q: query, limit } })
  return res.data
}

export async function fetchLiveStockBySymbol(symbol) {
  const res = await api.get('stocks/live-detail/', { params: { symbol } })
  return res.data
}

export async function fetchStockById(id) {
  const res = await api.get(`stocks/${id}/`)
  return res.data
}

export async function fetchHistoricalBySymbol(symbol, period = '1y', interval = '1mo') {
  const res = await api.get('stocks/historical/', { params: { symbol, period, interval } })
  return res.data
}

export async function fetchStockSentiment(symbol) {
  const res = await api.get('stocks/sentiment/', { params: { symbol }, timeout: 30000 })
  return res.data
}

export async function fetchStockPerformance5Y(symbol) {
  const res = await api.get('stocks/performance-5y/', { params: { symbol }, timeout: 30000 })
  return res.data
}

export function getStockDownloadUrl(symbol) {
  const base = import.meta.env.VITE_API_BASE_URL
  const access = localStorage.getItem('access')
  return `${base}stocks/download-summary/?symbol=${encodeURIComponent(symbol)}&token=${encodeURIComponent(access || '')}`
}

export async function downloadStockSummary(symbol) {
  const base = import.meta.env.VITE_API_BASE_URL
  const access = localStorage.getItem('access')
  const res = await fetch(`${base}stocks/download-summary/?symbol=${encodeURIComponent(symbol)}`, {
    headers: { Authorization: `Bearer ${access}` }
  })
  if (!res.ok) throw new Error('Download failed')
  const blob = await res.blob()
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${symbol}_summary.csv`
  a.click()
  URL.revokeObjectURL(url)
}

export async function setMpin(mpin) {
  const res = await api.post('mpin/set/', { mpin })
  return res.data
}

export async function verifyMpin(mpin) {
  const res = await api.post('mpin/verify/', { mpin })
  return res.data
}

export async function fetchAdminUsers() {
  const res = await api.get('admin/users/')
  return res.data
}

export async function fetchAdminUserPortfolios(userId) {
  const res = await api.get(`admin/users/${userId}/portfolios/`)
  return res.data
}

export async function adminDeletePortfolio(portfolioId) {
  await api.delete(`admin/portfolio/${portfolioId}/delete/`)
}
